// ifndef::backend-pdf[]
// = PostDoc in MBSE & DevOps (https://github.com/CoCoVaD/website/blob/master/docs/modules/ROOT/pages/postdoc.pdf[pdf version])
// endif::[]
= PostDoc in MBSE & DevOps
Jean-Michel Bruel <bruel@irit.fr>
v1.2, {localdate}

// ------ Changelog ------
// 1.0: First Draft
// 1.1: Yves feedback
// 1.2: Marc feedback

ifndef::backend-pdf[]

include::ROOT:page$definitions.adoc[]

[CAUTION]
====
image:https://img.shields.io/badge/Position-Closed-red[] 

The postdoc position has been filled 
====

endif::[]
ifdef::backend-pdf[]
include::definitions.adoc[]
endif::[]

*Keywords*::
MBSE; Model-Based Systems Engineering; Ontologies; DevOps; Requirements

The {cocovad} is hiring an *18 months Post-Doc position*.
Hold at {ut2j}, in collaboration with {irit} Laboratory, the project takes place in an industrial Chair with {Airbus}, the worldwide aeronautic leader. 

// *******************************************
== Collaborative & Continuous Value Delivery
// *******************************************

The chair aims at studying and making effective the complementarity between detailed data manipulation technologies with abstract and complex models and ontologies in an integrated and value-driven framework.
Despite the success of Model-Based Systems Engineering (MBSE) adoption, its application at scale and in a continuous approach to ensure the delivery of added value for its adopters is far from straightforward. 
The inherent complexity in terms of implied domains or of massively heterogeneous and poorly related data is not weaved by the simple use of a formal and disciplined modeling approach. 
A collaborative and continuous framework and process are required and need to aggregate up-to-date technologies in complementary techniques such as models, ontologies, and complex data management. 

// ******************** 
== Job details
// ********************

You will be a member of the {irit} laboratory and join the {Airbus} IDMR department, in charge of the Modeling & Simulation research program of the _Digital Design Manufacturing & Services_ (DDMS) transformation of the company.

The concrete issue we plan to solve in this project is to reduce the testing efforts induced by the increasing complexity of systems. While formal verification promises to relieve that effort, providing a formal specification is a difficult task. Focussing on requirements' and models' integration, the target outcome will be a continuously integrated framework supporting more amenable artifacts but still formal enough to increase the confidence that the system will pass certification tests. 
In that context, you will be responsible for the following main activities:

- Participate in the requirement elicitation and refinement, based on the state of the art and the various constraints
- Establishing a sandbox framework compatible with the project's cases studies and current applications
- Studying the current state of the art on ontologies, data-driven modeling, and their application to complex systems engineering
- Refining the initial project roadmaps
- Helping refine the upcoming PhDs' perimeters and missions

// ******************** 
== Who can apply?
// ********************

Outstanding candidates will have the opportunity to work on advanced topics.
{Airbus} intends to hire with a permanent contract (_CDI_ in French) the selected engineer at the end of the postdoc.
Candidates not interested in that possibility are asked not to submit.
The position does not require any security habilitation.

We are looking for a Post-Doc candidate with the following:

- A Ph.D. in either Model-Based or Systems Engineering (ideally both);
// - Experience in at least one concrete Systems Engineering domain (aeronautics preferably);
- Some industrial experience;
- Knowledge of language theory and model transformations;
- Autonomy in daily work;
- Ability to work within a small team and with an international network of collaborators;
- Aiming at regularly publishing in top venues;
- Excellent English skills (both spoken and written) for scientific communication (although French may undoubtedly be used for everyday life);
- Aiming at joining {Airbus} at the end of the postdoc to integrate the MBSE team and continue working on the Chaire activities.

// ***********************
== Where do we work?
// ***********************

The position will be held in the {iut} close-by {Airbus}' offices.
Toulouse is the capital of Occitanie and Aeronautics.  It is a well-connected city,
with lots of students and IT companies.
The funding is available for one year, with a possible extension of 6 months (for a total of 1.5 years), and amounts up to 4.000 €/month according to the candidate's experience.

// *******************
== How to apply? 
// *******************

For more information on the research and/or the position, please contact 
Jean-Michel Bruel (bruel@irit.fr), including a copy of your CV (with references).
Screening of potential candidates will start immediately and until the position is filled. 
The formal application requires:

* A full CV, including a publication list;
* A Cover Letter of max. two pages describing your skills, experience, and why you are the best candidate to hire for this project;
* A copy of the Ph.D. diploma (or report, if diploma not available yet);
* Optionally, some recommendation letters (up to three).

Please use "[CoCoVaD PostDoc]" in your email's subject to facilitate its processing.
Applications will start from the opening publication date and will continue until the position is filled. 
The selection will include an interview (most likely operated online) consisting of presenting the candidate's views on his own experience and the relevance for the project and early takeouts on the project's topic.
The {ut2j} promotes diversity in employment and welcomes applications from all sections of the community.

// ***************
== Key Infos 
// ***************

* Job offer: https://cocovad.github.io/website/cocovad/1.0/postdoc.html
* IRIT/CNRS website: https://www.irit.fr/en/home/
* SM@RT team website: https://smart-researchteam.github.io/

